"""Canonical bitwise/shift COLLAPSE identities, generated BY CONSTRUCTION (not
random search) so the high-frequency idioms real crypto/hash/mix code uses are
densely represented: self-inverse XOR ((a^B)^B -> a), double-NOT (~~a -> a),
idempotent AND/OR (t&t -> t, t|t -> t), self-XOR (t^t -> 0), and
complement-annihilation (a&~a -> 0, a|~a -> -1).

Each identity is exact (always holds), so the COLLAPSE root label is correct by
construction; the rest of the body is labelled by the sound oracles. The shifting
sub-expression B is varied over many shift amounts (incl. ones absent from the
enumerated superopt library, e.g. 5,6,7,9,11) and operand shapes, embedded among
distractor arithmetic and sometimes consumed downstream -- so the model learns
the STRUCTURAL cancellation, not a memorised shift constant. These are exactly
the COLLAPSE patterns the in-compiler bitwise/gf2 superoptimizer rewrites.
"""
import json
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import make_action_labels as A

COLLAPSE = 5
SHIFTS = [1, 2, 3, 4, 5, 6, 7, 9, 11, 13, 16, 17, 24, 31]
MASKS = [1, 3, 7, 15, 255, 65535, -1]


def emit_subexpr(rng, base, ctr, body):
    """Emit a random pure sub-expression of `base` (a value name); return its temp.
    Used as the cancelling operand B."""
    kind = rng.choice(["shl", "shr", "not", "and", "or", "xor", "var", "var"])
    if kind == "var":
        return base
    t = f"%b{ctr[0]}"; ctr[0] += 1
    if kind == "shl":
        body.append(f"{t} = {base} << {rng.choice(SHIFTS)}")
    elif kind == "shr":
        body.append(f"{t} = {base} >> {rng.choice(SHIFTS)}")
    elif kind == "not":
        body.append(f"{t} = {base} ^ -1")
    else:
        op = {"and": "&", "or": "|", "xor": "^"}[kind]
        body.append(f"{t} = {base} {op} {rng.choice(MASKS)}")
    return t


def gen_one(rng):
    nparams = rng.randint(2, 4)
    pnames = [f"@p{i}" for i in range(nparams)]
    body = []
    ctr = [0]
    live = list(pnames)
    for _ in range(rng.randint(0, 3)):
        op = rng.choice(["+", "-", "*", "&", "|", "^"])
        t = f"%d{ctr[0]}"; ctr[0] += 1
        body.append(f"{t} = {rng.choice(live)} {op} {rng.choice(live)}")
        live.append(t)

    a = rng.choice(live)
    # 3-variable collapses: a 2-var bitwise core that simplifies, combined with a
    # third var -- the realizer's superopt rooted at the final node still finds the
    # cheaper form. These cover patterns like ((x|y)^(x&y))|z -> (x^y)|z that the
    # 2-var corpus underrepresents.
    if len(live) >= 3 and rng.random() < 0.45:
        v = rng.sample(live, 3)
        a3, b3, c3 = v[0], v[1], v[2]
        core = rng.choice(["xoroa", "andcons", "orcons"])
        if core == "xoroa":                  # (a|b)^(a&b) -> a^b
            t1 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t1} = {a3} | {b3}")
            t2 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t2} = {a3} & {b3}")
            tc = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{tc} = {t1} ^ {t2}")
        elif core == "andcons":              # (a&b)|(a&~b) -> a
            t1 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t1} = {a3} & {b3}")
            nb = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{nb} = {b3} ^ -1")
            t2 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t2} = {a3} & {nb}")
            tc = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{tc} = {t1} | {t2}")
        else:                                # (a|b)&(a|~b) -> a
            t1 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t1} = {a3} | {b3}")
            nb = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{nb} = {b3} ^ -1")
            t2 = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{t2} = {a3} | {nb}")
            tc = f"%c{ctr[0]}"; ctr[0]+=1; body.append(f"{tc} = {t1} & {t2}")
        op = rng.choice(["|", "&", "^", "+"])
        root = f"%x{ctr[0]}"; ctr[0]+=1; body.append(f"{root} = {tc} {op} {c3}")
        root_idx = len(body) - 1
        if rng.random() < 0.5:
            t = f"%u{ctr[0]}"; ctr[0]+=1
            body.append(f"{t} = {root} {rng.choice(['+', '^', '&', '|'])} {rng.choice(live)}")
            ret = t
        else:
            ret = root
        body.append(f"return {ret}")
        return pnames, body, root_idx
    form = rng.choice(["xorinv", "xorinv", "xorinv", "dnot", "idem_and",
                       "idem_or", "selfxor", "and_notself", "or_notself"])
    if form == "xorinv":                      # (a ^ B) ^ B -> a
        b = emit_subexpr(rng, rng.choice(live), ctr, body)
        t1 = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{t1} = {a} ^ {b}")
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {t1} ^ {b}")
    elif form == "dnot":                       # ~~a -> a
        t1 = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{t1} = {a} ^ -1")
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {t1} ^ -1")
    elif form == "idem_and":                   # t & t -> t
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {a} & {a}")
    elif form == "idem_or":                    # t | t -> t
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {a} | {a}")
    elif form == "selfxor":                    # t ^ t -> 0
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {a} ^ {a}")
    elif form == "and_notself":                # a & ~a -> 0
        t1 = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{t1} = {a} ^ -1")
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {a} & {t1}")
    else:                                      # a | ~a -> -1
        t1 = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{t1} = {a} ^ -1")
        root = f"%x{ctr[0]}"; ctr[0] += 1; body.append(f"{root} = {a} | {t1}")
    root_idx = len(body) - 1

    if rng.random() < 0.5:
        t = f"%u{ctr[0]}"; ctr[0] += 1
        body.append(f"{t} = {root} {rng.choice(['+', '^', '&', '|'])} {rng.choice(live)}")
        ret = t
    else:
        ret = root
    body.append(f"return {ret}")
    return pnames, body, root_idx


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 16000
    out_path = sys.argv[2] if len(sys.argv) > 2 else "ident_train.jsonl"
    seed = int(sys.argv[3]) if len(sys.argv) > 3 else 404
    rng = random.Random(seed)
    w = open(os.path.join(HERE, out_path), "w", encoding="utf-8")
    counts = [0] * 6
    for sid in range(n):
        params, body, root_idx = gen_one(rng)
        acts = A.action_labels(body, params)
        acts[root_idx] = COLLAPSE
        for x in acts:
            counts[x] += 1
        w.write(json.dumps({"seed": sid, "params": params,
                            "funcs": [{"instrs": body, "action": acts}]}) + "\n")
    w.close()
    names = ["KEEP", "DELETE", "FOLD", "AFFINE", "GVN", "COLLAPSE"]
    print(f"wrote {n} fns -> {out_path}")
    print({names[i]: counts[i] for i in range(6)})


if __name__ == "__main__":
    main()
